from abc import ABC, abstractmethod
from typing import Optional

import pandas as pd


class TopicModelRepository(ABC):
    """
    Abstract base class defining the port for a topic model repository.
    """

    @abstractmethod
    def exists(self, model_name: str, dataset: str) -> bool:
        """
        A model is considered available if the minimal required files exist.
        Args:
            model_name: The name of the model to check.
            dataset: The name of the dataset used.
        Returns:
            True if the model data exists, False otherwise.
        """
        raise NotImplementedError

    @abstractmethod
    def load_model_info(self, model_name: str, dataset: str) -> Optional[pd.DataFrame]:
        """
        Load general information about the topic model.

        Args:
            model_name: The name of the model to load.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with model information.
        """
        raise NotImplementedError

    @abstractmethod
    def load_topics(self, model_name: str, dataset: str) -> Optional[pd.DataFrame]:
        """
        Load the topics generated by the model.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the topics.
        """
        raise NotImplementedError

    @abstractmethod
    def load_metrics(self, model_name: str, dataset: str) -> Optional[pd.DataFrame]:
        """
        Load the performance metrics of the model.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the model's metrics.
        """
        raise NotImplementedError

    @abstractmethod
    def load_params(self, model_name: str, dataset: str) -> Optional[pd.DataFrame]:
        """
        Load the parameters used to train the model.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the model's parameters.
        """
        raise NotImplementedError

    @abstractmethod
    def load_document_topics(
        self, model_name: str, dataset: str
    ) -> Optional[pd.DataFrame]:
        """
        Load the topic distribution for each document.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the document-topic distribution.
        """
        raise NotImplementedError

    @abstractmethod
    def load_topic_coordinates(
        self, model_name: str, dataset: str
    ) -> Optional[pd.DataFrame]:
        """
        Load the coordinates for visualizing topics in a 2D space.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the topic coordinates.
        """
        raise NotImplementedError

    @abstractmethod
    def load_best_hyperparams(
        self, model_name: str, dataset: str
    ) -> Optional[pd.DataFrame]:
        """
        Load the best hyperparameters found during optimization.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the best hyperparameters.
        """
        raise NotImplementedError

    @abstractmethod
    def load_hyperparams_trials(
        self, model_name: str, dataset: str
    ) -> Optional[pd.DataFrame]:
        """
        Load the results of all hyperparameter optimization trials.

        Args:
            model_name: The name of the model.
            dataset: The name of the dataset used.

        Returns:
            A pandas DataFrame with the hyperparameter trials.
        """
        raise NotImplementedError
