services:

  ingestion:
    build:
      context: ./backend-ingestion
    image: tfg-topics-ingestion
    container_name: tfg_topics_ingestion
    profiles:
      - ingestion
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATA_DIR=/data
      - REPOS_CSV_FILE_NAME=tfg_list.csv
    volumes:
      - ./data:/data

  processing:
    build:
      context: ./backend-processing
    image: tfg-topics-processing
    container_name: tfg_topics_processing
    profiles:
      - processing
    environment:
      - DATA_DIR=/data
    volumes:
      - ./data:/data