sonar.projectKey=zcc1001_tfg-topics
sonar.organization=zcc1001
sonar.projectName=tfg-topics
sonar.sourceEncoding=UTF-8

sonar.sources=backend-ingestion/src,backend-processing/src
sonar.tests=backend-ingestion/tests,backend-processing/tests

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,data/**,docs/**,build/**,dist/**,prototypes/**
sonar.coverage.exclusions=**/tests/**,**/__init__.py,frontend-web/src/**/*

sonar.python.version=3.10
sonar.python.coverage.reportPaths=backend-ingestion/coverage.xml,backend-processing/coverage.xml
